name: Publish Package

on:
  push:
    tags:
      - "v*" # triggers on tags like v0.1.2

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Install peer dependencies for build
        run: |
          npm install react-native-svg@^15.11.2 \
                      react-native-gesture-handler@^2.28.0 \
                      react-native-reanimated@^3.17.4 \
                      @types/react@^19.1.11 \
                      @types/react-native@^0.81.0 \
                      --legacy-peer-deps

      - name: Build package
        run: npm run build

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
